apiVersion: apps/v1
kind: Deployment
metadata:
  name: ride-share-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ride-share
  template:
    metadata:
      labels:
        app: ride-share
    spec:
      containers:
        - name: ride-share-container
          image: ${IMAGE_NAME}:${IMAGE_TAG::7}
          ports:
            - containerPort: 8080