name: Build Spring Boot App and Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: public.ecr.aws/p7g1n7k2/innovation/ride-share
      IMAGE_TAG: ${{github.sha}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set up JDK 17
        uses: actions/setup-java@v4.7.0
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build JAR with Maven
        run: mvn clean package -DskipTests

      - name: Verify JAR file
        run: ls -l target/

      # Configure AWS credentials (using AWS secrets)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Log in to Public ECR
      - name: Log in to Amazon ECR Public
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws

      # Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t ride-sharing:${IMAGE_TAG::7} .

      # Tag Docker image for Public ECR
      - name: Tag Docker Image for ECR
        run: |
          docker tag ride-sharing:${IMAGE_TAG::7} ${IMAGE_NAME}:${IMAGE_TAG}

      # Push Docker image to Public ECR
      - name: Push Docker Image to ECR
        run: |
          docker push public.ecr.aws/p7g1n7k2/innovation/ride-share:latest

      # Verify Docker image locally
      - name: Verify Docker Image
        run: docker images